name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - name: Install dependencies
      run: make ci-setup

    - name: Validate reference code
      run: |
        make reference-checks
        make reference-tests

  build-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build docker image
      run: make docker-image

    - name: Validate running the kata via docker
      run: |
        make in-docker TARGET=reference-checks
        make in-docker TARGET=reference-tests
        make in-docker TARGET=workspace-checks
